version: 2
updates:
  - package-ecosystem: "swift"
    directory: "ArchiverLib"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
