disabled_rules: # rule identifiers to exclude from running
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - PDFArchiver/Helpers/Payment/SwiftyLocalReceiptValidator.swift
  - Pods
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - unused_import
  - yoda_condition
