excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - ArchiverLib/.build
  - Shared/*

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - type_body_length
  - trailing_comma

opt_in_rules:
  - async_without_await
  - closure_end_indentation
  - closure_spacing
  - convenience_type
  - direct_return
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - final_test_case
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_condition_list
  - prefer_key_path
  - prefer_zero_over_explicit_init
  - private_action
  - private_swiftui_state
  # - private_outlet
  - redundant_nil_coalescing
  - redundant_self
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - sorted_first_last
  - sorted_imports
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

nesting:
  type_level:
    warning: 3
    error: 5

function_parameter_count: 10

identifier_name:
  allowed_symbols: "_"
  excluded: # excluded via string array
    - t
    - x
    - y
    - z
    - id
    - at
    - of
    - to

type_name:
  excluded:
    - ID
