excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - ArchiverLib/.build
  - Shared/*

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - type_body_length
  - trailing_comma

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  # - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - unavailable_function
  - yoda_condition

nesting:
  type_level:
    warning: 3
    error: 5

function_parameter_count: 10

identifier_name:
  allowed_symbols: "_"
  excluded: # excluded via string array
    - t
    - x
    - y
    - z
    - id
    - at
    - of
    - to

type_name:
  excluded:
    - ID
