//
//  CustomButton.swift
//  PDFArchiver
//
//  Created by Julian Kahnert on 03.04.19.
//  Copyright © 2019 Julian Kahnert. All rights reserved.
//

import UIKit

@IBDesignable
class CustomButton: UIButton {

    /// When positive, the background of the layer will be drawn with rounded corners. Also effects the mask generated by the `masksToBounds' property. Defaults to zero. Animatable.
    @IBInspectable var cornerRadius: Double {
        get {
            return Double(self.layer.cornerRadius)
        }
        set {
            self.layer.cornerRadius = CGFloat(newValue)
        }
    }
}
