# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Generate new localized screenshots"
lane :createNewScreenshots do
  capture_screenshots(
    scheme: "PDFArchiver")
  # upload_to_app_store(
  #   force: true,
  #   skip_binary_upload: true,
  #   skip_metadata: true)
end

desc "Upload binary to Sentry.io"
lane :sentry do
  download_dsyms(
    min_version: "2.0.0",
    output_directory: "build/"
  )
  sentry_upload_dsym(
    dsym_path: "build/"
  )
end

desc "Build Beta-Version & Upload it to TestFlight."
lane :beta do
  build_app
  changelog_from_git_commits
  upload_to_testflight(
    distribute_external: true,
    beta_app_description: "Current preview of the App!",
    beta_app_feedback_email: "beta@pdf-archiver.io",
    groups: ["alphatesters"])
  download_dsyms(
    version: "latest",
    output_directory: "build/"
  )
  sentry_upload_dsym(
    dsym_path: "build/"
  )
end

desc "Download metadata from App Store Connect."
lane :meta_download do
  sh 'deliver download_metadata'
  # sh 'deliver download_screenshots'
end

desc "Upload metadata to App Store Connect."
lane :meta_upload do
  deliver(
    skip_binary_upload: true,
    force: true,
    metadata_path: "./fastlane/metadata")
end

desc "Submit the latest build to the review prozess."
lane :submit_review do

  sh 'deliver download_metadata'

  deliver(
    skip_metadata: true,
    skip_binary_upload: true,
    skip_screenshots: true,
    submit_for_review: true,
    force: true,
    automatic_release: false)
end
